
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Courier_Service
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public static Connection con;
    public static Statement st5;
    public static PreparedStatement ps5 ;
    public Employee() {
        initComponents();
        try {
                con = DriverManager.getConnection("jdbc:derby://localhost:1527/Online_Curiar", "CuriarAdmin", "onlinecuriarpass");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
            }
    }
    public static ResultSet getData(String name) throws SQLException{
        ps5.setString(1, "%"+name+"%");
        return ps5.executeQuery();    
    }
    public void openTab0(){
        showEmployeeProfile();
        this.setVisible(true);
        jTabbedPane2.setSelectedIndex(0);
    }
    public void showEmployeeProfile(){
        Home h = new Home();
        String un =h.getUsername();
        try {
            String sql = "SELECT * FROM EMPLOYEE_INFO WHERE USERNAME ='"+un+"'";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            rs.next();
            EmployeeIDTextField.setText(rs.getString("ID"));
            EmployeeNameTextField.setText(rs.getString("NAME"));
            EmployeeMobileNoTextField.setText(rs.getString("MOBILENO"));
            EmployeeAddressTextField.setText(rs.getString("ADDRESS"));
            EmployeeAddressTextField1.setText(rs.getString("EMAIL"));
            EmployeeAddressTextField2.setText(rs.getString("AGE"));
        } catch (SQLException ex) {

        }
    }
    public void employeeTakeOrder(){
        try {
            String sql = "SELECT * FROM PENDING_ORDER";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            TakeOrderTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Can't show","Error",JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        EmployeeProfilePanel = new javax.swing.JPanel();
        jPanel87 = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        EmployeeIDTextField = new javax.swing.JTextField();
        EmployeeNameTextField = new javax.swing.JTextField();
        EmployeeMobileNoTextField = new javax.swing.JTextField();
        EmployeeAddressTextField = new javax.swing.JTextField();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        EmployeeAddressTextField1 = new javax.swing.JTextField();
        jLabel137 = new javax.swing.JLabel();
        EmployeeAddressTextField2 = new javax.swing.JTextField();
        jLabel138 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EmployeeTrackOrderPanel = new javax.swing.JPanel();
        jPanel96 = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        EmployeeSreachOrderButton = new javax.swing.JButton();
        EmployeeTrackOrderdIteamNameTextField = new javax.swing.JTextField();
        jLabel126 = new javax.swing.JLabel();
        EmployeeTrackOrderTextField = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        EmployeeTrackOrderStatusTextField = new javax.swing.JTextField();
        jLabel130 = new javax.swing.JLabel();
        EmployeeTrackOrderShowMassage = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        EmployeeTakeOrderTablePanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TakeOrderTable = new javax.swing.JTable();
        jLabel122 = new javax.swing.JLabel();
        EmployeeTakeOrderButton = new javax.swing.JButton();
        EmployeeTakeOrderTablePanel1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TakeOrderTable1 = new javax.swing.JTable();
        jLabel123 = new javax.swing.JLabel();
        jPanel91 = new javax.swing.JPanel();
        HomePageButton69 = new javax.swing.JButton();
        jLabel127 = new javax.swing.JLabel();
        UserPageButton19 = new javax.swing.JButton();
        EmployeePageButton20 = new javax.swing.JButton();
        HomePageButton70 = new javax.swing.JButton();
        HomePageButton71 = new javax.swing.JButton();
        HomePageButton72 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        UserPageButton20 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeProfilePanel.setBackground(new java.awt.Color(204, 255, 255));

        jPanel87.setBackground(new java.awt.Color(204, 255, 255));

        jLabel119.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel119.setText("My profile");

        jLabel133.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel133.setText("ID");

        EmployeeIDTextField.setEditable(false);
        EmployeeIDTextField.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        EmployeeNameTextField.setEditable(false);
        EmployeeNameTextField.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        EmployeeMobileNoTextField.setEditable(false);
        EmployeeMobileNoTextField.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        EmployeeAddressTextField.setEditable(false);
        EmployeeAddressTextField.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel134.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel134.setText("Name");

        jLabel135.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel135.setText("Mobile No");

        jLabel136.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel136.setText("Address");

        EmployeeAddressTextField1.setEditable(false);
        EmployeeAddressTextField1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel137.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel137.setText("Email");

        EmployeeAddressTextField2.setEditable(false);
        EmployeeAddressTextField2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel138.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel138.setText("Age");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-24.png"))); // NOI18N

        javax.swing.GroupLayout jPanel87Layout = new javax.swing.GroupLayout(jPanel87);
        jPanel87.setLayout(jPanel87Layout);
        jPanel87Layout.setHorizontalGroup(
            jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel87Layout.createSequentialGroup()
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel87Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel87Layout.createSequentialGroup()
                                .addComponent(jLabel137)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmployeeAddressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel87Layout.createSequentialGroup()
                                .addComponent(jLabel136)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmployeeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel87Layout.createSequentialGroup()
                                .addComponent(jLabel135)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmployeeMobileNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel87Layout.createSequentialGroup()
                                .addComponent(jLabel134, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmployeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel87Layout.createSequentialGroup()
                                .addComponent(jLabel133)
                                .addGap(104, 104, 104)
                                .addComponent(EmployeeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel87Layout.createSequentialGroup()
                                .addComponent(jLabel138)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmployeeAddressTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel87Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel119, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel87Layout.setVerticalGroup(
            jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel87Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel119))
                .addGap(53, 53, 53)
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel133)
                    .addComponent(EmployeeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel134))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeMobileNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel135))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeAddressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel137))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeAddressTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel138))
                .addGap(12, 12, 12)
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel136))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EmployeeProfilePanelLayout = new javax.swing.GroupLayout(EmployeeProfilePanel);
        EmployeeProfilePanel.setLayout(EmployeeProfilePanelLayout);
        EmployeeProfilePanelLayout.setHorizontalGroup(
            EmployeeProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EmployeeProfilePanelLayout.setVerticalGroup(
            EmployeeProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeProfilePanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jPanel87, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab0", EmployeeProfilePanel);

        EmployeeTrackOrderPanel.setBackground(new java.awt.Color(204, 255, 255));

        jPanel96.setBackground(new java.awt.Color(204, 255, 255));

        jLabel125.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel125.setText("Track Order");

        EmployeeSreachOrderButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        EmployeeSreachOrderButton.setForeground(new java.awt.Color(0, 0, 204));
        EmployeeSreachOrderButton.setText("Search");
        EmployeeSreachOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSreachOrderButtonActionPerformed(evt);
            }
        });

        EmployeeTrackOrderdIteamNameTextField.setEditable(false);
        EmployeeTrackOrderdIteamNameTextField.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel126.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel126.setText("Type Order ID");

        EmployeeTrackOrderTextField.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel129.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel129.setText("Ordered Iteam");

        EmployeeTrackOrderStatusTextField.setEditable(false);
        EmployeeTrackOrderStatusTextField.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel130.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel130.setText("Order Status");

        EmployeeTrackOrderShowMassage.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        EmployeeTrackOrderShowMassage.setForeground(new java.awt.Color(255, 0, 0));

        jButton4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 204));
        jButton4.setText("Refreah");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel96Layout = new javax.swing.GroupLayout(jPanel96);
        jPanel96.setLayout(jPanel96Layout);
        jPanel96Layout.setHorizontalGroup(
            jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel96Layout.createSequentialGroup()
                .addGroup(jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel96Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel125, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel96Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel96Layout.createSequentialGroup()
                                .addComponent(jLabel126, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmployeeTrackOrderTextField))
                            .addGroup(jPanel96Layout.createSequentialGroup()
                                .addGroup(jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel130)
                                    .addComponent(jLabel129))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(EmployeeSreachOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel96Layout.createSequentialGroup()
                .addGroup(jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel96Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmployeeTrackOrderShowMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel96Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeeTrackOrderdIteamNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EmployeeTrackOrderStatusTextField))))
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel96Layout.createSequentialGroup()
                .addGap(0, 309, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(284, 284, 284))
        );
        jPanel96Layout.setVerticalGroup(
            jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel96Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel125, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel126)
                    .addComponent(EmployeeTrackOrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeSreachOrderButton))
                .addGap(111, 111, 111)
                .addGroup(jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeTrackOrderdIteamNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel129))
                .addGap(18, 18, 18)
                .addGroup(jPanel96Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeTrackOrderStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel130))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeTrackOrderShowMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton4)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EmployeeTrackOrderPanelLayout = new javax.swing.GroupLayout(EmployeeTrackOrderPanel);
        EmployeeTrackOrderPanel.setLayout(EmployeeTrackOrderPanelLayout);
        EmployeeTrackOrderPanelLayout.setHorizontalGroup(
            EmployeeTrackOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeTrackOrderPanelLayout.createSequentialGroup()
                .addComponent(jPanel96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmployeeTrackOrderPanelLayout.setVerticalGroup(
            EmployeeTrackOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeTrackOrderPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jPanel96, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", EmployeeTrackOrderPanel);

        EmployeeTakeOrderTablePanel.setBackground(new java.awt.Color(204, 255, 255));

        TakeOrderTable.setBackground(new java.awt.Color(255, 255, 204));
        TakeOrderTable.setBorder(new javax.swing.border.MatteBorder(null));
        TakeOrderTable.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        TakeOrderTable.setForeground(new java.awt.Color(0, 0, 0));
        TakeOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Iteam", "Sender Name", "Sender Mobile", "Receiver Name", "Receiver Mobile", "Receiver Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TakeOrderTable.setAutoscrolls(false);
        TakeOrderTable.setSelectionBackground(new java.awt.Color(0, 204, 204));
        TakeOrderTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TakeOrderTable.setSurrendersFocusOnKeystroke(true);
        TakeOrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TakeOrderTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(TakeOrderTable);

        jLabel122.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel122.setText("Take Order");

        EmployeeTakeOrderButton.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        EmployeeTakeOrderButton.setForeground(new java.awt.Color(51, 153, 255));
        EmployeeTakeOrderButton.setText("Take");
        EmployeeTakeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeTakeOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeTakeOrderTablePanelLayout = new javax.swing.GroupLayout(EmployeeTakeOrderTablePanel);
        EmployeeTakeOrderTablePanel.setLayout(EmployeeTakeOrderTablePanelLayout);
        EmployeeTakeOrderTablePanelLayout.setHorizontalGroup(
            EmployeeTakeOrderTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeTakeOrderTablePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(EmployeeTakeOrderTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeTakeOrderTablePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeTakeOrderTablePanelLayout.createSequentialGroup()
                        .addComponent(EmployeeTakeOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252))))
            .addGroup(EmployeeTakeOrderTablePanelLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel122, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmployeeTakeOrderTablePanelLayout.setVerticalGroup(
            EmployeeTakeOrderTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeTakeOrderTablePanelLayout.createSequentialGroup()
                .addGap(0, 147, Short.MAX_VALUE)
                .addComponent(jLabel122, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(EmployeeTakeOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        jTabbedPane2.addTab("tab2", EmployeeTakeOrderTablePanel);

        EmployeeTakeOrderTablePanel1.setBackground(new java.awt.Color(204, 255, 255));

        TakeOrderTable1.setBackground(new java.awt.Color(255, 255, 204));
        TakeOrderTable1.setBorder(new javax.swing.border.MatteBorder(null));
        TakeOrderTable1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        TakeOrderTable1.setForeground(new java.awt.Color(0, 0, 0));
        TakeOrderTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order_No", "Sender", "Receiver", "Delivery_Address", "Iteam", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TakeOrderTable1.setAutoscrolls(false);
        TakeOrderTable1.setSelectionBackground(new java.awt.Color(0, 204, 204));
        TakeOrderTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TakeOrderTable1.setSurrendersFocusOnKeystroke(true);
        TakeOrderTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TakeOrderTable1MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(TakeOrderTable1);
        if (TakeOrderTable1.getColumnModel().getColumnCount() > 0) {
            TakeOrderTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            TakeOrderTable1.getColumnModel().getColumn(3).setMinWidth(150);
        }

        jLabel123.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel123.setText("My Orders");

        javax.swing.GroupLayout EmployeeTakeOrderTablePanel1Layout = new javax.swing.GroupLayout(EmployeeTakeOrderTablePanel1);
        EmployeeTakeOrderTablePanel1.setLayout(EmployeeTakeOrderTablePanel1Layout);
        EmployeeTakeOrderTablePanel1Layout.setHorizontalGroup(
            EmployeeTakeOrderTablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeTakeOrderTablePanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(EmployeeTakeOrderTablePanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmployeeTakeOrderTablePanel1Layout.setVerticalGroup(
            EmployeeTakeOrderTablePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeTakeOrderTablePanel1Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );

        jTabbedPane2.addTab("tab3", EmployeeTakeOrderTablePanel1);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, -30, 686, 860));

        jPanel91.setBackground(new java.awt.Color(255, 102, 0));

        HomePageButton69.setBackground(new java.awt.Color(102, 204, 255));
        HomePageButton69.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        HomePageButton69.setForeground(new java.awt.Color(0, 0, 204));
        HomePageButton69.setText("Messages");
        HomePageButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageButton69ActionPerformed(evt);
            }
        });

        jLabel127.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel127.setForeground(new java.awt.Color(0, 0, 204));
        jLabel127.setText("Menu");

        UserPageButton19.setBackground(new java.awt.Color(102, 204, 255));
        UserPageButton19.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        UserPageButton19.setForeground(new java.awt.Color(0, 0, 204));
        UserPageButton19.setText("Take Order");
        UserPageButton19.setPreferredSize(new java.awt.Dimension(55, 28));
        UserPageButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPageButton19ActionPerformed(evt);
            }
        });

        EmployeePageButton20.setBackground(new java.awt.Color(102, 204, 255));
        EmployeePageButton20.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        EmployeePageButton20.setForeground(new java.awt.Color(0, 0, 204));
        EmployeePageButton20.setText("Track Order");
        EmployeePageButton20.setPreferredSize(new java.awt.Dimension(55, 28));
        EmployeePageButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeePageButton20ActionPerformed(evt);
            }
        });

        HomePageButton70.setBackground(new java.awt.Color(102, 204, 255));
        HomePageButton70.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        HomePageButton70.setForeground(new java.awt.Color(0, 0, 204));
        HomePageButton70.setText("My Profile");
        HomePageButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageButton70ActionPerformed(evt);
            }
        });

        HomePageButton71.setBackground(new java.awt.Color(102, 204, 255));
        HomePageButton71.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        HomePageButton71.setForeground(new java.awt.Color(0, 0, 204));
        HomePageButton71.setText("Log Out");
        HomePageButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageButton71ActionPerformed(evt);
            }
        });

        HomePageButton72.setBackground(new java.awt.Color(102, 204, 255));
        HomePageButton72.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        HomePageButton72.setForeground(new java.awt.Color(0, 0, 204));
        HomePageButton72.setText("Terms & Conditions");
        HomePageButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomePageButton72ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 153, 255));
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        UserPageButton20.setBackground(new java.awt.Color(102, 204, 255));
        UserPageButton20.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        UserPageButton20.setForeground(new java.awt.Color(0, 0, 204));
        UserPageButton20.setText("My Orders");
        UserPageButton20.setPreferredSize(new java.awt.Dimension(55, 28));
        UserPageButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPageButton20ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 153, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel91Layout = new javax.swing.GroupLayout(jPanel91);
        jPanel91.setLayout(jPanel91Layout);
        jPanel91Layout.setHorizontalGroup(
            jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel91Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(HomePageButton72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomePageButton71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomePageButton69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeePageButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserPageButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomePageButton70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserPageButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addGroup(jPanel91Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel127, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel91Layout.setVerticalGroup(
            jPanel91Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel91Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(95, 95, 95)
                .addComponent(jLabel127, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(HomePageButton70, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserPageButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserPageButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmployeePageButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HomePageButton69, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HomePageButton71, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HomePageButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        getContentPane().add(jPanel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeSreachOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSreachOrderButtonActionPerformed
        // Employee Track Order
        EmployeeTrackOrderShowMassage.setText("");
        String id = EmployeeTrackOrderTextField.getText();
        try {
            String sql = "SELECT * FROM ALL_ORDER WHERE ORDER_ID = '"+id+"'";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            rs.next();
            EmployeeTrackOrderdIteamNameTextField.setText(rs.getString(2));
            EmployeeTrackOrderStatusTextField.setText(rs.getString(9));
            EmployeeTrackOrderShowMassage.setText("Order Found");

        } catch (SQLException ex) {
            EmployeeTrackOrderdIteamNameTextField.setText("");
            EmployeeTrackOrderStatusTextField.setText("");
            EmployeeTrackOrderShowMassage.setText("Invalid Order ID");
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_EmployeeSreachOrderButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        EmployeeTrackOrderShowMassage.setText("");
        EmployeeTrackOrderTextField.setText("");
        EmployeeTrackOrderdIteamNameTextField.setText("");
        EmployeeTrackOrderStatusTextField.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TakeOrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TakeOrderTableMouseClicked
        // Table Mouse Clicked Info

    }//GEN-LAST:event_TakeOrderTableMouseClicked

    private void EmployeeTakeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeTakeOrderButtonActionPerformed
        // Employeee Take Order
        String  id = JOptionPane.showInputDialog(null, "Enter Order ID");
        Home h = new Home();
        String eun = h.getUsername();
        
        try {
            //Insert into Completed Order table From All Order Table
            String sql3 = "SELECT * FROM ALL_ORDER WHERE ORDER_ID = '"+id+"'";
            PreparedStatement st3 = con.prepareStatement(sql3);
            ResultSet rs3 = st3.executeQuery();
            rs3.next();

            String oid = rs3.getString(1);
            String i = rs3.getString(2);
            String un1 = rs3.getString(3);
            String sn1 = rs3.getString(4);
            String smn1 = rs3.getString(5);
            String rn1 = rs3.getString(6);
            String rmn1 = rs3.getString(7);
            String ocb = rs3.getString(8);

            String sql4 = "INSERT INTO COMPLETED_ORDER (ORDER_ID, SENDER_NAME, SENDER_MOBILE, RECEIVER_NAME, RECEIVER_MOBILE, USERNAME, COMPLETED_BY, ITEAM) VALUES(?,?,?,?,?,?,?,?)";
            PreparedStatement ps4 = con.prepareStatement(sql4);
            //Show Completed Order To Admin
            ps4.setString(1, oid);
            ps4.setString(2, sn1);
            ps4.setString(3, smn1);
            ps4.setString(4, rn1);
            ps4.setString(5, rmn1);
            ps4.setString(6, un1);
            ps4.setString(7, ocb);
            ps4.setString(8, i);
            
            ps4.executeUpdate();
            System.out.println("Completed Order Table Created");
            
            // Delete row from  Employee Take_Order  and Pending_order Table
            String sql = "DELETE FROM PENDING_ORDER WHERE ORDER_ID = '"+id+"'";
            PreparedStatement st = con.prepareStatement(sql);
            st.execute();
            System.out.println("Value Deleted From PENDING_ORDER Table");

            String sql1 = "DELETE FROM TAKE_ORDER WHERE ORDER_ID = '"+id+"'";
            PreparedStatement st1 = con.prepareStatement(sql1);
            st1.execute();
            System.out.println("Value Deleted From TAKE_ORDER Table");

            employeeTakeOrder();

            //Update Admin All Order Table
            String sql2 = "UPDATE ALL_ORDER SET PICKED = ?, STATUS = ? WHERE ORDER_ID = '"+id+"'";
            PreparedStatement ps2 = con.prepareStatement(sql2);
            ps2.setString(1, eun);
            ps2.setString(2, "Completed");
            ps2.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"This Order Not Available!","Information",JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_EmployeeTakeOrderButtonActionPerformed

    private void HomePageButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageButton69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomePageButton69ActionPerformed

    private void UserPageButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPageButton19ActionPerformed
        // TODO add your handling code here:
        employeeTakeOrder();
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_UserPageButton19ActionPerformed

    private void EmployeePageButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeePageButton20ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_EmployeePageButton20ActionPerformed

    private void HomePageButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageButton70ActionPerformed
        // TODO add your handling code here:
        openTab0();
    }//GEN-LAST:event_HomePageButton70ActionPerformed

    private void HomePageButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageButton71ActionPerformed
        // TODO add your handling code here:
        dispose();
        Home h = new Home();
        h.OpenTab4();
    }//GEN-LAST:event_HomePageButton71ActionPerformed

    private void HomePageButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomePageButton72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomePageButton72ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TakeOrderTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TakeOrderTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TakeOrderTable1MouseClicked

    private void UserPageButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPageButton20ActionPerformed
        try {
            // TODO add your handling code here:
            st5 = con.createStatement();
            ps5 = con.prepareStatement("select * from all_order where picked like ?");
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Home h = new Home();
        String un =h.getUsername();
        
        DefaultTableModel dtm = (DefaultTableModel) TakeOrderTable1.getModel();
        //removing previous row in the table
        int r = TakeOrderTable1.getRowCount();
        while(r--> 0){
            dtm.removeRow(r);
        }
        
        try {
            // Getting data from database
            ResultSet rs = getData(un);
            // Inserting rows while result set is not empty
            while(rs.next()){
                // using vector to insert row
                java.util.Vector v = new java.util.Vector();
                v.add(rs.getString("order_id"));
                v.add(rs.getString("sender_name"));
                v.add(rs.getString("receiver_name"));
                v.add(rs.getString("receiver_address"));
                v.add(rs.getString("iteam"));
                v.add(rs.getString("status"));
                
                dtm.addRow(v);
                jTabbedPane2.setSelectedIndex(3);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database Error");
        }
    }//GEN-LAST:event_UserPageButton20ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int si = jTabbedPane2.getSelectedIndex();
        if(si == 1 || si == 2 || si == 3)
            jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmployeeAddressTextField;
    private javax.swing.JTextField EmployeeAddressTextField1;
    private javax.swing.JTextField EmployeeAddressTextField2;
    private javax.swing.JTextField EmployeeIDTextField;
    private javax.swing.JTextField EmployeeMobileNoTextField;
    private javax.swing.JTextField EmployeeNameTextField;
    private javax.swing.JButton EmployeePageButton20;
    private javax.swing.JPanel EmployeeProfilePanel;
    private javax.swing.JButton EmployeeSreachOrderButton;
    private javax.swing.JButton EmployeeTakeOrderButton;
    private javax.swing.JPanel EmployeeTakeOrderTablePanel;
    private javax.swing.JPanel EmployeeTakeOrderTablePanel1;
    private javax.swing.JPanel EmployeeTrackOrderPanel;
    private javax.swing.JLabel EmployeeTrackOrderShowMassage;
    private javax.swing.JTextField EmployeeTrackOrderStatusTextField;
    private javax.swing.JTextField EmployeeTrackOrderTextField;
    private javax.swing.JTextField EmployeeTrackOrderdIteamNameTextField;
    private javax.swing.JButton HomePageButton69;
    private javax.swing.JButton HomePageButton70;
    private javax.swing.JButton HomePageButton71;
    private javax.swing.JButton HomePageButton72;
    private javax.swing.JTable TakeOrderTable;
    private javax.swing.JTable TakeOrderTable1;
    private javax.swing.JButton UserPageButton19;
    private javax.swing.JButton UserPageButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JPanel jPanel87;
    private javax.swing.JPanel jPanel91;
    private javax.swing.JPanel jPanel96;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
